# Generated by Django 3.2.2 on 2021-07-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.CharField(max_length=15)),
                ('Title', models.CharField(max_length=100)),
                ('Content', models.TextField()),
                ('Hit', models.IntegerField()),
                ('Success_per', models.IntegerField()),
                ('Reg_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Code_History',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.CharField(max_length=15)),
                ('Board_idx', models.IntegerField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Judge_State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_idx', models.IntegerField()),
                ('UserID', models.CharField(max_length=15)),
                ('States', models.CharField(max_length=5)),
                ('Memory_use', models.IntegerField()),
                ('Time_Complex', models.IntegerField()),
                ('Submission_Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=15)),
                ('PW', models.CharField(max_length=32)),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
            ],
        ),
    ]
