# Generated by Django 3.1.3 on 2021-08-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfoj_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='Hit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='Reg_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='Success_per',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='judge_state',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
