# Generated by Django 3.1.3 on 2021-08-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfoj_system', '0003_auto_20210824_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='UserID',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
