# Generated by Django 3.1.3 on 2021-08-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfoj_system', '0004_board_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('useremail', models.CharField(max_length=128)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User_Table',
        ),
        migrations.AlterField(
            model_name='board',
            name='UserID',
            field=models.CharField(default='anonymous', max_length=15),
        ),
    ]
