# Generated by Django 3.1.3 on 2021-09-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfoj_system', '0006_auto_20210825_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='UserID',
            new_name='user_id',
        ),
    ]
