# Generated by Django 3.1.3 on 2021-09-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfoj_system', '0007_auto_20210903_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='Title',
            new_name='title',
        ),
    ]
