# Generated by Django 3.1.3 on 2021-09-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfoj_system', '0008_auto_20210903_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='Reg_date',
            new_name='reg_date',
        ),
    ]
