# Generated by Django 3.1.3 on 2021-09-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfoj_system', '0009_auto_20210912_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='Hit',
            field=models.IntegerField(default=0),
        ),
    ]
