# Generated by Django 3.1.3 on 2021-09-14 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfoj_system', '0010_board_hit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='Hit',
            new_name='hit',
        ),
    ]
